image: $CI_REGISTRY_IMAGE

variables:
  CMAKE_PREFIX_PATH: /opt/Qt/6.4.0/gcc_64

build_and_test:
  stage: build
 
  script:
  
     # build cpp
    - cd ./prj/cpp && ./build.sh

    # run c++ tests
    - ./test.sh

    # ensure mysql service is running and create database
    - sudo ./db_init.sh

    - cd ../python/prj && ./venv_create.sh

    # run python test
    - cd .. &&  sudo ./prj/venv/bin/pytest test/test__client.py::test_multiple_cpp_procs --capture=sys -s
    


  artifacts:
      paths:
        - ./prj/cpp/build/my_app_main
        - ./prj/app/build/test_results.xml
        - ./prj/cpp/build/ctest_results.xml

      reports:
        junit: ./prj/cpp/build/test_results.xml




 
